apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.registry.location }}/backend:latest"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
{{ if .Values.registry.useSecret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }} 
{{ end }}